name: Linux
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: main
    paths:
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/c-cpp.yml'
  pull_request:
    branches: main
    paths:
    - '**'
    - '!**.yml'
    - '!/**.md'
    - '**/c-cpp.yml'

jobs:
  build:
    name: ${{ matrix.build.name }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: ubuntu-22.04-gcc-
            os: ubuntu-22.04
            cc: gcc
          #- name: ubuntu-22.04-clang
            #os: ubuntu-22.04
            #cc: clang

    runs-on: ${{ matrix.build.os }}
    container: ${{ matrix.build.container }}
    env:
      CC: '${{ matrix.build.cc }}'
      NETPANZER_DATADIR: ${{ github.workspace }}/data
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - if: ${{ env.CC }}
      run: |
        if [ "$CC" = "gcc" ]; then
          CXX=g++
        else
          CXX=clang++
        fi
        echo "CXX=${CXX}" >> $GITHUB_ENV

    - name: Show info
      run: |
        export -p
        echo '${{ toJSON(matrix) }}'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt remove -y firefox
        sudo apt upgrade -y
        sudo apt install -y \
          build-essential \
          libboost-dev \
          ruby-dev \
          scons \
          swig \
          libx11-dev \
          libxmu-dev \
          libxxf86vm-dev \
          libxrandr-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libpng-dev \
          libjpeg-dev

    - name: Build ClanLib
      run: |
        cd external/clanlib
        scons

    - name: Build with scons
      run: |
        scons
